# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)



# whole_questionsのデータをテーブルに挿入
  # 必須項目
WholeQuestion.create(content: 'これまでで一番嬉しかったことは？', required: 'true')
WholeQuestion.create(content: 'これまでで一番苦しかったことは？', required: 'true')
WholeQuestion.create(content: 'これまでを振り返って一番感謝していることは？', required: 'true')
WholeQuestion.create(content: 'これまでで一番影響を受けた人物は？', required: 'true')
WholeQuestion.create(content: '今一番情熱をもっていることは？', required: 'true')
  # 任意追加質問(最大２０個の追加とする)
WholeQuestion.create(content: '印象に残っている出来事/思い出をなんでも追加してください', required: 'false') 
WholeQuestion.create(content: '印象に残っている出来事/思い出をなんでも追加してください', required: 'false') 
WholeQuestion.create(content: '印象に残っている出来事/思い出をなんでも追加してください', required: 'false') 
WholeQuestion.create(content: '印象に残っている出来事/思い出をなんでも追加してください', required: 'false') 
WholeQuestion.create(content: '印象に残っている出来事/思い出をなんでも追加してください', required: 'false') 
WholeQuestion.create(content: '印象に残っている出来事/思い出をなんでも追加してください', required: 'false') 
WholeQuestion.create(content: '印象に残っている出来事/思い出をなんでも追加してください', required: 'false') 
WholeQuestion.create(content: '印象に残っている出来事/思い出をなんでも追加してください', required: 'false') 
WholeQuestion.create(content: '印象に残っている出来事/思い出をなんでも追加してください', required: 'false') 
WholeQuestion.create(content: '印象に残っている出来事/思い出をなんでも追加してください', required: 'false') 
WholeQuestion.create(content: '印象に残っている出来事/思い出をなんでも追加してください', required: 'false') 
WholeQuestion.create(content: '印象に残っている出来事/思い出をなんでも追加してください', required: 'false') 
WholeQuestion.create(content: '印象に残っている出来事/思い出をなんでも追加してください', required: 'false') 
WholeQuestion.create(content: '印象に残っている出来事/思い出をなんでも追加してください', required: 'false') 
WholeQuestion.create(content: '印象に残っている出来事/思い出をなんでも追加してください', required: 'false') 
WholeQuestion.create(content: '印象に残っている出来事/思い出をなんでも追加してください', required: 'false') 
WholeQuestion.create(content: '印象に残っている出来事/思い出をなんでも追加してください', required: 'false') 
WholeQuestion.create(content: '印象に残っている出来事/思い出をなんでも追加してください', required: 'false') 
WholeQuestion.create(content: '印象に残っている出来事/思い出をなんでも追加してください', required: 'false') 
WholeQuestion.create(content: '印象に残っている出来事/思い出をなんでも追加してください', required: 'false') 


# detailed_questionsのデータをテーブルに挿入
  # 必須項目
DetailedQuestion.create(whole_question_id: '1', content: '一番嬉しかったこと')
DetailedQuestion.create(whole_question_id: '1', content: 'なぜそれほど嬉しかったのか')
DetailedQuestion.create(whole_question_id: '2', content: '一番苦しかったこと')
DetailedQuestion.create(whole_question_id: '2', content: 'なぜそれほど苦しかったのか')
DetailedQuestion.create(whole_question_id: '3', content: '感謝していること')
DetailedQuestion.create(whole_question_id: '3', content: 'なぜそれほど感謝しているのか')
DetailedQuestion.create(whole_question_id: '4', content: '影響を受けた人物名と、その人物の何が特別／特徴だったか')
DetailedQuestion.create(whole_question_id: '4', content: 'どんな影響を受けたのか')
DetailedQuestion.create(whole_question_id: '5', content: '今情熱をもっていること')
DetailedQuestion.create(whole_question_id: '5', content: 'なぜ熱中しているのか')
  # 任意追加質問
DetailedQuestion.create(whole_question_id: '6', content: '出来事タイトル/何があったか')
DetailedQuestion.create(whole_question_id: '6', content: 'その時感じたこと/考えたこと/行動したこと')
DetailedQuestion.create(whole_question_id: '7', content: '出来事タイトル/何があったか')
DetailedQuestion.create(whole_question_id: '7', content: 'その時感じたこと/考えたこと/行動したこと')
DetailedQuestion.create(whole_question_id: '8', content: '出来事タイトル/何があったか')
DetailedQuestion.create(whole_question_id: '8', content: 'その時感じたこと/考えたこと/行動したこと')
DetailedQuestion.create(whole_question_id: '9', content: '出来事タイトル/何があったか')
DetailedQuestion.create(whole_question_id: '9', content: 'その時感じたこと/考えたこと/行動したこと')
DetailedQuestion.create(whole_question_id: '10', content: '出来事タイトル/何があったか')
DetailedQuestion.create(whole_question_id: '10', content: 'その時感じたこと/考えたこと/行動したこと')
DetailedQuestion.create(whole_question_id: '11', content: '出来事タイトル/何があったか')
DetailedQuestion.create(whole_question_id: '11', content: 'その時感じたこと/考えたこと/行動したこと')
DetailedQuestion.create(whole_question_id: '12', content: '出来事タイトル/何があったか')
DetailedQuestion.create(whole_question_id: '12', content: 'その時感じたこと/考えたこと/行動したこと')
DetailedQuestion.create(whole_question_id: '13', content: '出来事タイトル/何があったか')
DetailedQuestion.create(whole_question_id: '13', content: 'その時感じたこと/考えたこと/行動したこと')
DetailedQuestion.create(whole_question_id: '14', content: '出来事タイトル/何があったか')
DetailedQuestion.create(whole_question_id: '14', content: 'その時感じたこと/考えたこと/行動したこと')
DetailedQuestion.create(whole_question_id: '15', content: '出来事タイトル/何があったか')
DetailedQuestion.create(whole_question_id: '15', content: 'その時感じたこと/考えたこと/行動したこと')
DetailedQuestion.create(whole_question_id: '16', content: '出来事タイトル/何があったか')
DetailedQuestion.create(whole_question_id: '16', content: 'その時感じたこと/考えたこと/行動したこと')
DetailedQuestion.create(whole_question_id: '17', content: '出来事タイトル/何があったか')
DetailedQuestion.create(whole_question_id: '17', content: 'その時感じたこと/考えたこと/行動したこと')
DetailedQuestion.create(whole_question_id: '18', content: '出来事タイトル/何があったか')
DetailedQuestion.create(whole_question_id: '18', content: 'その時感じたこと/考えたこと/行動したこと')
DetailedQuestion.create(whole_question_id: '19', content: '出来事タイトル/何があったか')
DetailedQuestion.create(whole_question_id: '19', content: 'その時感じたこと/考えたこと/行動したこと')
DetailedQuestion.create(whole_question_id: '20', content: '出来事タイトル/何があったか')
DetailedQuestion.create(whole_question_id: '20', content: 'その時感じたこと/考えたこと/行動したこと')
DetailedQuestion.create(whole_question_id: '21', content: '出来事タイトル/何があったか')
DetailedQuestion.create(whole_question_id: '21', content: 'その時感じたこと/考えたこと/行動したこと')
DetailedQuestion.create(whole_question_id: '22', content: '出来事タイトル/何があったか')
DetailedQuestion.create(whole_question_id: '22', content: 'その時感じたこと/考えたこと/行動したこと')
DetailedQuestion.create(whole_question_id: '23', content: '出来事タイトル/何があったか')
DetailedQuestion.create(whole_question_id: '23', content: 'その時感じたこと/考えたこと/行動したこと')
DetailedQuestion.create(whole_question_id: '24', content: '出来事タイトル/何があったか')
DetailedQuestion.create(whole_question_id: '24', content: 'その時感じたこと/考えたこと/行動したこと')
DetailedQuestion.create(whole_question_id: '25', content: '出来事タイトル/何があったか')
DetailedQuestion.create(whole_question_id: '25', content: 'その時感じたこと/考えたこと/行動したこと')